### PR TITLE
Add cocnent

### PR DESCRIPTION
**Pull request by fantasticsoul**
Add cocnent

### CODE REVIEW

**Comment by olegrjumin** [comment]
Hey thanks for the addition, looks awesome! 
Could you please check [CONTRIBUTING.md](https://github.com/olegrjumin/awesome-react-state-management/blob/master/CONTRIBUTING.md)

**Comment by fantasticsoul** [comment]
GITHUB_REPOSITORY_NAME: concent
GITHUB_REPOSITORY_LINK: https://github.com/concentjs/concent
GITHUB_REPOSITORY_DESCRIPTION: About
State management that tailored for react, it is simple, predictable, progressive and efficient.

**Comment by olegrjumin** [comment]
@fantasticsoul Could you add it yourself to the list, as described in the contributing.md, keeping alphabetical order?
In a form:
```- [GITHUB_REPOSITORY_NAME](GITHUB_REPOSITORY_LINK) - GITHUB_REPOSITORY_DESCRIPTION```

Thanks, if contributing.md file is confusing, please let me know, what part should be changed

**Comment by olegrjumin** [comment]
@fantasticsoul could you update your PR?

**Pull request merged**
